version: 2

updates:
  # Single monthly PR with majors + minors + patches for root package.json
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "07:00"
      timezone: Europe/Copenhagen
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 1
    groups:
      all-deps:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]
    labels: ["dependencies"]
    commit-message:
      prefix: "deps(app)"
      include: scope

  # One monthly PR for all GitHub Actions updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "07:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 1
    groups:
      all-actions:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]
    labels: ["dependencies"]
