name: CI

on: pull_request

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Node Modules
        run: npm install

      - name: Build Vue/Typescript
        run: npm run build
   
