name: Deploy to Github Pages  # Defines the name of the GitHub Actions workflow.

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
    build:
      name: Build  # Defines the name of the build job.
      runs-on: ubuntu-latest  # Specifies the operating system for the job.

      steps:
        - name: Checkout Repo  # Checks out the repository.
          uses: actions/checkout@v4

        - name: Create Node Environment  # Sets up Node.js environment.
          uses: actions/setup-node@v4
          with: 
            node-version: 20.x

        - name: Install Packages and Build Application  # Installs npm packages and builds the Vue.js application.
          run: |
            npm ci
            npm run build

        - name: Setup Pages  # Configures pages for deployment.
          id: pages
          uses: actions/configure-pages@v4

        - name: Upload artifact  # Uploads the build artifact.
          uses: actions/upload-pages-artifact@v3
          id: deployment
          with:
            path: dist/
      
    deploy:
      needs: build
      permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
          with:
            preview: true